all: null no_free size_100 post_free funny_free vector

null: null.c
	gcc null.c -o null -Wall -g

no_free: no_free.c
	gcc no_free.c -o no_free -Wall -g

size_100: size_100.c
	gcc size_100.c -o size_100 -Wall -g

post_free: post_free.c
	gcc post_free.c -o post_free -Wall -g

funny_free: funny_free.c
	gcc funny_free.c -o funny_free -Wall -g

vector: vector.c
	gcc vector.c -o vector -Wall -g