all: p1 p2 p3 p4 p5 p6 p7 p8

clean:
	rm -rf p1 p2 p3 p4 p5 p6 p7 p8

p1: p1.c
	gcc p1.c -o p1 -Wall

p2: p2.c
	gcc p2.c -o p2 -Wall

p3: p3.c
	gcc p3.c -o p3 -Wall

p4: p4.c
	gcc p4.c -o p4 -Wall

p5: p5.c
	gcc p5.c -o p5 -Wall

p6: p6.c
	gcc p6.c -o p6 -Wall

p7: p7.c
	gcc p7.c -o p7 -Wall

p8: p8.c
	gcc p8.c -o p8 -Wall